### ISSUE TITLE
Moissonnage de l'Alternative Export dans la V1 de l'API ODS

### ISSUE THREAD

**Issue by IshanB** [opendatateam/udata-ods#12]
OpenDataSoft a finalement mis l'Alternative Export et les Pièces attachées dans leur API version 1 (mais pas encore la version 2)
Il faudrait donc updater le moissonneur pour prendre en compte ces fichiers.
Un exemple : le GTFS n'est pas moissonné dans le cas de ce jeu de données : https://opendata.lillemetropole.fr//explore/dataset/transport_arret_transpole-point/download?format=csv&timezone=Europe/Berlin&use_labels_for_header=true

Merci !

**Comment by abulte** [comment]
Thanks @IshanB I'm tackling this ASAP.

**Comment by abulte** [comment]
@IshanB this should be available in the next release, hopefully this week.
