### ISSUE TITLE
Make resource titles language-agnostic

### ISSUE THREAD

**Issue by micael-grilo** [opendatateam/udata-ods#19]
This line generates resource titles with default language in French,

https://github.com/opendatateam/udata-ods/blob/5b6b810d34de1263e0d466a41279f76daed68cea/udata_ods/harvesters.py#L175

For non French users it would be nice have a standard title, like for example the (dataset.title + JSON/XML/etc..), something like:

```python
resource.title = dataset.title + " - " + label
```

Or if there's another suggestion, let me know, I would be glad to help with this.
Best!

**Comment by noirbizarre** [comment]
I think this is possible to localize the string:
```python
resource.title = _('{format} export').format(format=label)
```

Each translation found in any active plugin is automatically loaded.

**Comment by noirbizarre** [comment]
I think this simply need to be translatable and translated, ie:
```python
resource.title = _('{format} format export').format(format=label)
```

Translations found in every active plugin are automatically loaded so I think we should start internationalizing `udata-ods` (even if it's for only one translatable string).
