### ISSUE TITLE
Dataset update frequency is not harvested

### ISSUE THREAD

**Issue by restuccia** [opendatateam/udata-ods#235]
https://github.com/opendatateam/udata-ods/blob/70518b31f3832aa5c5e08341b641905a767de548/udata_ods/harvesters.py#L154

Seems to me that the metadata on update frequency is not harvested, and the harvester sets it to `unknown` every time it runs. 

The ods instance on data.economie.gouv.fr has a `periodicity` custom metadata that seems to match our `frequency`, perhaps we could investigate on this?

**Comment by maudetes** [comment]
Thank you for this issue. Closing in favor of https://github.com/etalab/data.gouv.fr/issues/950 :) I copied your comment there
