### ISSUE TITLE
shapefiles with more than 50000 data

### ISSUE THREAD

**Issue by steplebr** [opendatateam/udata-ods#25]
There is a problem in opendatasoft platform when exporting large dataset in shapefiles (it appears on this dataset : https://www.data.gouv.fr/fr/datasets/adresse-et-geolocalisation-des-etablissements-denseignement-du-premier-et-second-degres-1/).
![big shape](https://user-images.githubusercontent.com/16958828/38297853-fce33474-37f5-11e8-9180-2232e3c074d7.png)

On their website, a large dataset has no shapefile link (the link is disabled). Automatically generating shapefiles url leads to partial file with only 50000 records. What should be done is : if it is possible to read dataset size, disabled shapefile export for large datasets, otherwise disabled shapefile export on opendatasoft harvester.

**Comment by abulte** [comment]
Hi @steplebr, thanks for reporting this. We'll look into it.

**Comment by abulte** [comment]
This should be fixed by #26. It'll be available on data.gouv.fr at our next production release.
